#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X_SPARK EDITION V-II ORIGINAL™ 
# Copyright (C) 2014 K1ks
# X00DEFAULT
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`; fi 

PMB=/data/ModBoost/X00DEFAULT.log;

if [ -e $PMB ]; then
busybox	rm $PMB;
fi;

busybox touch $PMB;
busybox echo "# NITRO X_SPARK EDITION" | tee -a $PMB;
busybox echo "" | tee -a $PMB;
busybox echo "# STARTING UP OF NITRO X : $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PMB;
busybox echo "" | tee -a $PMB;

busybox sysctl -e -w kernel.random.read_wakeup_threshold=128;
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256;

busybox sleep 1

if [ /proc/sys/kernel/random/read_wakeup_threshold=128 ]; then
busybox echo "...Optimization Nitro X Level : Default = Activated..." | tee -a $PMB; else
busybox echo "...Optimization Nitro X Level : Default = Not Activated..." | tee -a $PMB;
fi;

busybox echo "" | tee -a $PMB;
busybox echo "# END OF THE NITRO X : $( date +"%m-%d-%Y %H:%M:%S" ) " | tee -a $PMB
