#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X_SPARK EDITION V-II ORIGINAL™ 
# Copyright (C) 2014 K1ks
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`; fi 

PMB=/data/ModBoost/X00RENICE.log

if [ -e $PMB ]; then
busybox	rm $PMB;
fi

busybox touch $PMB;
busybox echo "# NITRO X_SPARK EDITION" | tee -a $PMB;
busybox echo "" | tee -a $PMB;
busybox echo "# STARTING UP OF NITRO X : $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PMB;
busybox echo "" | tee -a $PMB;

# Renice System Apps
renice -20 `pidof com.android.phone`
renice -18 `pidof com.android.contacts`
renice -18 `pidof com.android.mms`
renice -18 `pidof com.android.systemui`
renice -4 `pidof android.process.acore`
killall -9 `pidof android.process.media`

busybox echo "" | tee -a $PMB;
busybox echo "...Optimization Renice System = Activated..." | tee -a $PMB
busybox echo "" | tee -a $PMB;
busybox echo "# END OF THE NITRO X : $( date +"%m-%d-%Y %H:%M:%S" ) " | tee -a $PMB

