#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X ENGINE SERIES
# VERSION SPARK EDITION
# DEV BY K1KS
# X01BOOST 
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`; fi

PMB=/data/ModBoost/X01BOOST.log

if [ -e $PMB ]; then
busybox	rm $PMB;
fi

busybox touch $PMB;
busybox echo "*** NITRO X ENGINE ***" | tee -a $PMB;
busybox echo "" | tee -a $PMB;
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Executing X01BOOST..." | tee -a $PMB;
busybox echo "" | tee -a $PMB;

mem=$((`awk '/MemTotal/{print $2}' /proc/meminfo`/1024));

busybox echo "...Your Ram is $mem ..." | tee -a $PMB;

# LowMemoryKiller
if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
busybox	chown root:root /sys/module/lowmemorykiller/parameters/adj;
busybox	echo "0,3,6,9,12,15" > /sys/module/lowmemorykiller/parameters/adj;
fi;

if [ -e /sys/module/lowmemorykiller/parameters/minfree ]; then
busybox	chown root:root /sys/module/lowmemorykiller/parameters/minfree;
busybox	echo "3072,6144,9216,14336,20480,25600" > /sys/module/lowmemorykiller/parameters/minfree;
fi;

busybox echo "...Optimization LowMemoryKiller NitroX = Active..." | tee -a $PMB;

# VM Tweaks
busybox chown root:root /proc/sys/vm;
busybox echo "0" > /proc/sys/vm/laptop_mode;
busybox echo "0" > /proc/sys/vm/block_dump;
busybox echo "1" > /proc/sys/vm/oom_dump_tasks;
busybox echo "3" > /proc/sys/vm/page-cluster;
busybox echo "5120" > /proc/sys/vm/min_free_kbytes;
busybox echo "0" > /proc/sys/vm/oom_kill_allocating_task;
busybox echo "50" > /proc/sys/vm/swappiness;
busybox echo "70" > /proc/sys/vm/vfs_cache_pressure;
busybox echo "500" > /proc/sys/vm/dirty_expire_centisecs;
busybox echo "1000" > /proc/sys/vm/dirty_writeback_centisecs;
busybox echo "50" > /proc/sys/vm/dirty_background_ratio;
busybox echo "50" > /proc/sys/vm/dirty_ratio;
busybox echo "4" > /proc/sys/vm/min_free_order_shift;
busybox echo "1" >/proc/sys/vm/overcommit_memory;
busybox echo "50" >/proc/sys/vm/overcommit_ratio
busybox echo "512" > /sys/devices/virtual/bdi/default/read_ahead_kb;
busybox echo "10" > /proc/sys/fs/lease-break-time;
busybox echo "0" > /proc/sys/vm/panic_on_oom;
busybox echo "0" > /proc/sys/kernel/panic;
busybox echo "0" > /proc/sys/kernel/panic_on_oops;
busybox echo "3" > /proc/sys/vm/page-cluster; 
busybox sysctl -w kernel.random.write_wakeup_threshold=128;
busybox sysctl -w kernel.random.read_wakeup_threshold=1376;

if [ /proc/sys/vm/min_free_kbytes=5120 ]; then
busybox echo "...Optimization Kernel / VM Tweaks NitroX = Active..." | tee -a $PMB; else
busybox echo "...Optimization Kernel / VM Tweaks NitroX = Not Active..." | tee -a $PMB;
fi;

busybox echo "" | tee -a $PMB;
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) X01BOOST is Successfully Executed..." | tee -a $PMB;



