#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X ENGINE SERIES
# VERSION SPARK EDITION
# DEV BY K1KS
# X07ZIP 
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`; fi

PMB=/data/ModBoost/X07ZIP.log
ZIPALIGNDB=/data/zipalign.db
SYSTEM=$(mount|grep "/system "|awk '{ print $1 }')
function mountrw {
  mount | grep "/system " | grep rw >/dev/null || mount -o remount,rw $SYSTEM /system
}
function mountro {
  mount | grep "/system " | grep ro >/dev/null || mount -o remount,ro $SYSTEM /system
}

[ -e $PMB ] && rm $PMB
[ -f $ZIPALIGNDB ] || touch $ZIPALIGNDB

busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Executing X07ZIP..." | tee -a $PMB
busybox echo "" | tee -a $PMB

for DIR in /system/app /data/app /data/app-private ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
      echo "...Already OK : $DIR/$APK" | tee -a $PMB
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "...Already Zipalign : $DIR/$APK" | tee -a $PMB
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "...Now Zipalign : $DIR/$APK" | tee -a $PMB
        zipalign -f 4 $APK /cache/$APK
        mountrw
        cp -f -p /cache/$APK $APK
        rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

mountro
busybox touch $ZIPALIGNDB
busybox echo "" | tee -a $PMB
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) X07ZIP is Successfully Executed..." | tee -a $PMB

