#!/system/bin/sh
# PROJECT MOD BOOST EDITION  
# NITRO X ENGINE SERIES
# VERSION SPARK EDITION
# DEV BY K1KS
# X00NITRO 
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`; fi

PMB=/data/ModBoost/X00NITRO.log

if [ -e $PMB ]; then
busybox	rm $PMB;
fi;

busybox touch $PMB;
busybox echo "*** NITRO X ENGINE ***" | tee -a $PMB;
busybox echo "" | tee -a $PMB;
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Executing X00NITRO..." | tee -a $PMB;
busybox echo "" | tee -a $PMB;

if [ -e /system/xbin/haveged ]; then
busybox rm -f /dev/haveged.pid
haveged
busybox echo "...Nitro X Entropy = OK..." | tee -a $PMB; else
busybox echo "...Nitro X Entropy = Not OK..." | tee -a $PMB;
fi;
if
busybox touch /dev/haveged.pid
haveged
busybox renice -9 `busybox pidof haveged`; then
busybox echo "...Nitro X Entropy = Active..." | tee -a $PMB; else
busybox echo "...Nitro X Entropy = Not Active..." | tee -a $PMB;
fi;

busybox echo "" | tee -a $PMB;
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) X00NITRO is Successfully Executed..." | tee -a $PMB;