#!/system/bin/sh
#Clear audio+ Activation by ibanez7

sleep 60

# Keep Sony Clear audio+ technology in zone ram
PPID=$(pidof com.sonyericsson.music)
echo "-17" > /proc/$PPID/oom_adj
renice -18 $PPID
PPID=$(pidof com.sonyericsson.soundenhancement)
echo "-17" > /proc/$PPID/oom_adj
renice -18 $PPID